# Generated by Django 4.1.3 on 2023-01-17 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('cedula', models.IntegerField()),
                ('carrera', models.CharField(max_length=80)),
                ('curso', models.CharField(max_length=80)),
                ('fecha', models.DateField()),
                ('email', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=80)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipoestudiante')),
            ],
        ),
    ]
